name: Application Build

on:
  workflow_call:
    inputs:
      registry:
        description: Docker registry link
        required: true
        type: string
    secrets:
      image_tags:
        description: Tags required for docker image
        required: true
      REGISTRY_USERNAME:
        required: true
        description: Registry username
      REGISTRY_PASSWORD:
        required: true
        description: Registry password 

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.image_tags }}
          file: ./Dockerfile